name: After release

on:
  release:
    types: [published]

jobs:
  update_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout na release
        uses: actions/checkout@v3
        with:
          ref: release
      
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Use Node.js v14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install npm 8.3.0
        run: npm install -g npm@8.3.0

      - name: Update the project version on package.json
        run: npm version ${{ github.event.release.tag_name }} --no-git-tag-version

      - name: Commit changes in the release
        run: |
          git add package-lock.json
          git add package.json
          git commit --message "[skip ci] ${{ github.event.release.tag_name }}"
          git push origin release

  create_release_branch:
    runs-on: ubuntu-latest
    
    needs: update_release

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: release
      
      - name: Create the tag branch
        run: |
          git checkout -b ${{ github.event.release.tag_name }}
          git push

  create_pr_main:
    runs-on: ubuntu-latest
    
    needs: update_release

    steps:
      - name: Create Pull Request on Release
        uses: thomaseizinger/create-pull-request@1.2.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release
          base: main
          title: 'Liberação da release ${{ github.event.release.tag_name }}'
          body: ${{ github.event.release.body }}

